### ISSUE TITLE
Question about setting up the POS standalone

### ISSUE THREAD

**Issue by jeffmerkey** [openthc/pos#5]
Hi.  I have cloned your repo and run composer and npm and configured the httpd server and the site has an active cert.  When I go to run the pos from the website 1)  the config-examples.php file was blank and I had to 2) use the file from the /app tree to create a config.php file.  I am seeing another error now which is "{"meta":{"detail":"Not Found [CLA-037]"}}".  Is there a wiki somewhere that lists the simple steps to get the pos running quickly on Red Hat EL8?   We use our own in house rewards program for customers of our cannabis dispensary and your POS is ideal for our needs because it provides the source code so we can add our enhancements.

When I see the error the following url is displayed in the url field of the browser:

https://pos.moonliterewards.com/oauth2/authorize?scope=pos%20company%20contact&state=0637356f6c14270300abe632c7ae8ad3&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fpos.moonliterewards.com%2Fauth%2Fback%3Fr%3D%252Fdashboard&client_id=pos.moonliterewards.com

Any help would be appreciated.  Is this error is due to not being connected to metrc or biotrack?

Thanks

Jeff

**Comment by djbusby** [comment]
Does not seem like a Metrc/BT related error.  Please give us a few days to poke at this one.

**Comment by mashiox** [comment]
Help Desk Reference: Ops#62287

**Comment by codenameEm** [comment]
Is it working now as an update ?
Is the developer still up for this ?

**Comment by mashiox** [comment]
> Is it working now as an update ? Is the developer still up for this ?

It is unclear what update you are looking for. The problem encountered in this issue had to do with the authentication engine. We have solved this problem, and will be closing out this issue.

The POS application is still in active development. You may want to check out the docker environment, which includes the POS app, to see how the whole environment works together. https://github.com/openthc/docker
